name: Say Hello

on: pull_request

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Say hello in a PR comment
        uses: trendyminds/github-actions-pr-comments@master
        with:
          body: |
            Hello, there! **Welcome** to a great comment posted by our friendly bot helper!

            - Here
            - is
            - a
            - list
          github_token: ${{secrets.GITHUB_TOKEN}}
